name: POI Submission
description: Submit a new POI to the PlanetPOI registry
title: "[SUBMISSION] "
labels: ["poi-submission"]

body:
  - type: markdown
    attributes:
      value: |
        This submission is intended to be created from the PlanetPOI client.
        Review the prefilled data and click **Submit new issue**.

  - type: input
    id: cmdr
    attributes:
      label: Reported by (CMDR)
      placeholder: CmdrExample
    validations:
      required: true

  - type: textarea
    id: poi_json
    attributes:
      label: POI JSON (v=1)
      description: The POI payload. Do not include `active`.
      render: json
      placeholder: |
        {"v":1,"system":"HIP 36601","body":"C 3 a","lat":-68.234567,"lon":137.891234,"description":"Crystalline shards (Polonium)"}
    validations:
      required: true
